apiVersion: v1
kind: Service
metadata:
  name: gemline-server
  namespace: gemline
spec:
  type: ClusterIP
  selector:
    app: gemline-server
  ports:
    - name: http
      port: 80
      targetPort: http
