---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: infisical-gateway-environment
  namespace: external-secrets
spec:
  encryptedData:
    enrollment-token: AgBGU6gz+5+CqBLZyNZI5KQTz7iIvhOLLOBWvXbgkPZoC1lK3mZtdRdnanBrfOMIUiqvk68JXM5M3zPfS/OnA73XLUv23uU1v0q4+VOHww7TFnV1fYaBrWVuiWpGMe9Fq3UBsJ2av7Iy7ji6ANqdqv4Lpf0iubwytVs4mDoxptEr0gxu4TSExoD8lEAvIemazKQA8m0nYCj1Xp0gZCJwuC/0SkXA96I9WNoiogRIIsPaeMRYG3HPC2Q1kFw8aCHZPOvn3OpI2hID9q2pFf3RSYgrHykL0gNOdaaFEn/tJn5JekASOIoDvfG2YpvZ0g2/GK3qOvUrbGFc1Dj2SFnfphnMgQG5AtmA6DjdJovuH9wWcOFksVsf6VMhRN7eCLIyH9hkof/hSMmGijtduCtAT8EbnfJttiKXsXIL/g/7GlbtWqdksFB9M82jdOkuLhjgtysM/uPCcWwFQT0UahoOrtoq80a2JegycKZC2OhMxlMHXG8FSGW78KoCZ9oYNRViYGkJGxwbbiQKA+9a6kJDwj7Ov1BH3t/ohdEAZmdshsMtbpM20UAjZVwF5+VFEHAWxHCfj/gaNfoTX81xDqZ1BM2VPE4GoFcVRGVP15oT+aE2DxDce7sZx6zC+mjxeeo7x7SFF6ChMGNFRkPeJFdxLeEi+W5GESufTBm2N2Ri/9dOp2Pm9D91WWD9xGOUD312Zs0kUkskpILknMu+7r7kaN3Dic3u/Uy7ZQzWIPrA4R75Mw60pCSCYhSbDFe8l3WHpw==
  template:
    metadata:
      name: infisical-gateway-environment
      namespace: external-secrets
