---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: infisical-auth
  namespace: external-secrets
spec:
  encryptedData:
    clientId: AgCpzbAayl6fyhR2Whmcs6MJRlr1Ub8iy8T0ycpyX9Od2Zkl92vTzso0fJhp86xo5aFE6WMEEnhrblRz4Ln+NwU5zswn2QXSz/Vk96ckVg6Ia2N3la4xX/JjivrmBgmszOn8hzLOCufisDfNyzentcgE8h2irYpY7tguHgENIg8qPKt8IHPUPy4/ycBBNb01s2C3lbftjA4IK8WryTuH8C2829rVpyQMsezBPilns4XKKmFor62vQ4HgajHwUEsEGQTHVfgdQpVr+bL/V4QGkuROMYI3571+pKOSHN14lI+jXTFkUUGaLM877ADRUI6CTmaXNTj0T4zoNLgb5f+QdDmM1T4hUjGZ/6jIm60r449KDCU5U1ThH5hSzx1QxbSqZBHY0V67OSP0UtWezLdGpgqpDMbaHZcvZWdJqsVcxqVU9NUvtYOdNZhFrsXSxjeWBe+K7wXOxoEsq9hYzQRUzjwwpCWDvdKICTPBpJ+oVkLCkNJlziZajfAYXmgIuEqgB+yUS6zRsO+Vm+h4FDaHLcpC/3WqzPbY3mxUhGxphHwouMUTlbHrQjNxoC++ihv5XJtp9+dtW9Q4dDoFCI19jZppFz9EQEbxrc+LCxuSXMUIi+IqiYdbjZlwuwjKqKJ0aNhA2kBhbTh+7MYcsvAbLjvk0P/YiZ+rxAsiGL0f2FQxNAJMP8OKVa/Mra7uWyaDUFUV5WZTld5BvXGOn9RCxdUYfnC5veF19Gz/MhfF3LYczKbaiMs=
    clientSecret: AgAqkJPA0MxMC//cSKrJu50DSFg38lPRlFoAXihlFY7rG0eCa17ZKLZ0PKO4koyy0nqrBmhUV/fZgh1kLgVyVc148kgs7DZTua7cNpwzKoE12pE/SzEYX4pn2ExwiLH/IVcdN86UQgcB38xxGMlt2r0vh6Tvm59DEeMg8uRJd2Gy6tf3u1l/dt1KaCUbbZ+7GTlv+IGocZ/7JAhwgtfStGj5KzP9Ny+E45HSAJEeJpUj0YkDgbxlr+/nHIa0rSU7o/wny0SxD1BbRzrmUfPMDPHLBIKBwmRaXO3bUwVqaK0DsJR84es+dzcygh63vVptaJxp34+YwtQFD83quFboAmi/w5N2pKHUe6xy6lQJXo6pFzwPjaoEBO0bXjF9ci8Ke37Y5YfQ/0KgNactrFKHy+KbFT5AU6uSUP8JxfSbBq6+MaVyLcaiXfK0zcd4BqJ6rL5JUGKdnpqQ0idypvdAUgjQxg/QHJ+VBmBRS05Z5r8xKFkelHrq7rk3swsZcHovuHYFUCqsQ/hlyZvapPwlBxxP7DxvQsETbiE8QQnVuSyk27LKI8mgwO5viyZ+h7Q0v7rYO5sYCJV84DGGKG5xoaIfibbbUvNosKuVd/6Y5LzkFgMjTsEAIr2tUTXlAePxfaBI44K5EXGVVt5OQAmH6InEMQiH6f9Mk+c5qVQIvBSJefRbQ66osqw5V6eMj7mTsnPmhb6vUZpF4OWXNkJ66n+83I9sLZ8AUWtf/j1/N3yiwQyZgIvTOG9NmmK/HxeDH7IudRH4ZFt7NBYqJHlsW1Vr
  template:
    metadata:
      name: infisical-auth
      namespace: external-secrets
    type: Opaque
