---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: infisical-gateway-token
  namespace: external-secrets
spec:
  encryptedData:
    token: AgA+GORuUTa2IjNGvJ/djH+u+g6qi2PceqQjTGGUwRDZnB+rG7lp7sZwSci5CsE8Y2Carj4QirKumlqij4ZSiHsWF9PQfKHgtNQACj+5xNaiygM5c+gbTCxIxIXthyAeyc4Qa/n4kUEfKdB6+WDTqVmI6UXytunoU4SqQQxuzy21Zk8kZ/ke9mKPymWwQbifiY1L3TjwXZFOl0mYr+UhT5+PVhVam29aSCwSLNkvTbUIUfIFLPj/aKUvKVy7eWu8qnxQpgSn6IvKBQA5WXj6L5oWBJz7QO5DAiox+4ICu9JYPoYDs67wat+KL8QlkjEqgixbq2mCXlQrF2v/iyC+pd2OE6SEJ7ARcTnB0uCkY9N7aJbxeJyMPHxThm6nkkcC1cTfv2zzPA9Rnj9BSNcDAqOxMGvc0rNPA7K7GLDcCQ+hnPSsidnwdHPnjH5IAETdYQnFygsK37bR0dMki1MtuXN6YUm4WNEPgS0p6Q5CY8mPKB0EWZLxlmFEvRCOw5P4+A92Dg/cDrsO+wcqwoGw5RKa5RcMSX+tMqWtDoTQI9J/NuvXoj1YfPBQl6hHpRbVqRNFzOAERgremps/QLX4pdYOyKUBdztg1gwimWN27UVTnqE/WEgjq84CDHgh9k7fBYJ32yilGHuwBRMom9cI4JHxuQjQh59iqFI3weGwC8y0GVS7vTBf91tdtWuYYaHQu51xKJC4+BJYYSyU0CyEWjiGgUKwk6YNs2oLcu8M0dAonx4+/q14WUh2wFPfHMwd2w==
  template:
    metadata:
      name: infisical-gateway-token
      namespace: external-secrets
