---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: infisical-gateway-environment
  namespace: external-secrets
spec:
  encryptedData:
    enrollment-token: AgCNnCouEAKro3DIugLmweoztwZ/Kd01Sqqv9m+5/0rPj6Dbz+1n4dfvQR1ZlgmWlfdADLW1WS5ZBk50JeF1qjRvIg9qcDiVKPxsWWcBhkWkrNnHjJXQo8ztqmMOn40lyuETx/CJMujb4OFUGMtq8jU2EbzYWBBtWL1InA48E4Y00bL+JoD0V2OySKuH4Xx+EAIzf6IDdKTvpTv7zx04QVHWDVrm3pUDaK+05tsLi5A1jxMaBTnzhJTysXacb+2X5KkTve5gqT6A7zjNRkOcAX96oJgWLUrzfgD6O1pHWJIJJPyGI7uZi6KZnTNXD4TH7Z05QRw4GENucb1uQ9z4WygO1n0UuEuI1HITjk85mRUAgjH6yc2WJTQGASFXuO4q6HyfmgUFsz+BR7wpOJzhHUReN0I94RZl762yQbJ+U3dH6cU+v0mSvn5zgvMSAUpoZAytiUTGL12kWN8F01oPL+gbKVBuIfw9LXMgZDgQ8TIyqSLBx58vxYq7246uxE4XLgXdPtPZ7VVQnqcOtqC7zJm0dMVdqMBwFVsXuK/Zv36lQSa5sGd7H5x+E0qwFamdE9eNuc/uovWMwqYBtvcXBbBpoTjgOBweNIS79yMLmCAoH7rjdIs12iz+2EbidvWymhyE1GnPDdh7nZ9uN++b4JMWu0EnOYqrR0G+m13/QkkDEfDbM/+xgfzWGb54927K+nSXb28OoQy+UpBdH2F6cRsWKlbLaUbQ4O/807dwypXY477MyOHjA3Fd5I3LUVxvPA==
  template:
    metadata:
      name: infisical-gateway-environment
      namespace: external-secrets
