apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gemline
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/Alexis-Marcel/gemline.git
    targetRevision: main
    path: deploy/k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: gemline

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
